/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekti;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Besnik
 */
public class AdminForma extends javax.swing.JFrame {

    /**
     * Creates new form AdminForma
     */
    private Connection con;
    private Statement st;
    private ResultSet rs;
    
    public AdminForma() {
        initComponents();
         Shfaq_Listen_E_Userave();
         con=ConnectionManager.getConnection();
    }
    
            public void close(){
                WindowEvent closeEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
                Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeEvent);
            }
            
            public void clear(){
                username.setText("");
                password.setText("");
                roli.setText("");
            }
       
            
            public ArrayList<User> userList(){
                ArrayList<User> userList = new ArrayList<User>();
                con = ConnectionManager.getConnection();
                
                String query="select*from loginUsers";
                try {
                    st=con.createStatement();
                    rs=st.executeQuery(query);
                    User user;
                    while(rs.next()){
                        user = new User(rs.getInt("ID"),rs.getString("username"),rs.getString("password"),rs.getString("roli"));
                        userList.add(user);
                        
                    }
                }catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e);
                }
                
                return userList;
            }
            
             public void Shfaq_Listen_E_Userave(){
                ArrayList<User> list = userList();
                DefaultTableModel model = (DefaultTableModel)tabela.getModel();
                Object[] row = new Object[4];
                for(int i=0;i<list.size();i++){
                    row[0]=list.get(i).getID();
                    row[1]=list.get(i).getUsername();
                    row[2]=list.get(i).getPassword();
                    row[3]=list.get(i).getRoli();
                    model.addRow(row);
                }
            }
             
            public void ekzekutoSQLQuery(String query,String message){
                
              
                
                try {
                    st=con.createStatement();
                    if(!(roli.getText().equals("Admin")) && !(roli.getText().equals("Puntor/e"))){
                        JOptionPane.showMessageDialog(this, "Roli duhet te jete Admin ose Puntor/e",
                                "Error",JOptionPane.ERROR_MESSAGE);
                         
                    }else if((st.executeUpdate(query))==1){
                         
                        //refresh table 
                        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
                        model.setRowCount(0);
                         Shfaq_Listen_E_Userave();
                          JOptionPane.showMessageDialog(this, "Useri u "+message+" me sukses");
                         
                        }else{
                         JOptionPane.showMessageDialog(this, "Useri nuk u " +message+ " me sukses");
                    }
                } catch (Exception ae) {
                     JOptionPane.showMessageDialog(this, 
                             "Provoni nje username dhe password tjeter!","Warning"
                             ,JOptionPane.WARNING_MESSAGE);
                }
            } 
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton6 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        roli = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_arrow_left_32.png"))); // NOI18N
        jButton6.setText("Back");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        save.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        save.setText("Save");
        save.setFocusable(false);
        save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jToolBar1.add(save);

        delete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_1.png"))); // NOI18N
        delete.setText("Delete");
        delete.setFocusable(false);
        delete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jToolBar1.add(delete);

        clear1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        clear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clear1.setText("Clear");
        clear1.setFocusable(false);
        clear1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });
        jToolBar1.add(clear1);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1490737231_Print.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 10, 640, 80);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 120, 120, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 100, 30);
        getContentPane().add(username);
        username.setBounds(230, 120, 140, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 232, 640, 10);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Lista e userave te krijuar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 250, 190, 40);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Roli"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 250, 360, 210);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Roli");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 200, 40, 20);
        getContentPane().add(roli);
        roli.setBounds(230, 200, 140, 30);
        getContentPane().add(password);
        password.setBounds(230, 160, 140, 30);

        setSize(new java.awt.Dimension(655, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        close();
        Login l = new Login();
        l.setVisible(true);
         dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
      clear();
    }//GEN-LAST:event_clear1ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int i = tabela.getSelectedRow();
        TableModel model = tabela.getModel();
        username.setText(model.getValueAt(i,1).toString());
        password.setText(model.getValueAt(i,2).toString());
        roli.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String query="insert into loginUsers (username,password,roli) values('"+username.getText()+"','"+password.getText()+"','"+roli.getText()+"')";
            if(username.getText().isEmpty() || password.getText().isEmpty() 
                                 || roli.getText().isEmpty()){
                              JOptionPane.showMessageDialog(this, "Plotesoni fushat" 
                                      ,"Warning",JOptionPane.WARNING_MESSAGE);
                              return;
                    }    
            ekzekutoSQLQuery(query,"krijua");
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       String query="delete from loginUsers where username = '"+username.getText()+"'";
       if(username.getText().isEmpty() || password.getText().isEmpty() 
                                 || roli.getText().isEmpty()){
                              JOptionPane.showMessageDialog(this, "Zgjedhni cilin user deshiorni ta fshini" ,
                                      "Warning",JOptionPane.WARNING_MESSAGE);
                              return;
                    } 
       Object[] options = {"Yes","No"};
                int n = JOptionPane.showOptionDialog(this, "A deshironi ta fshini kete user",
                        "Zgjedh", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
                if(n==0){
                 ekzekutoSQLQuery(query,"fshi");
                  clear();
                }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            MessageFormat header = new MessageFormat("Userat e printuar");
            MessageFormat footer  = new MessageFormat("Page{0,number,integer}");
        
        try {
                    tabela.print(JTable.PrintMode.NORMAL, header, footer);
                
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n ", e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear1;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField roli;
    private javax.swing.JButton save;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
