/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekti;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Besnik
 */
public class FakturatDalse extends javax.swing.JInternalFrame {

    /**
     * Creates new form FakturatDalse
     */
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    private Statement st;
    Vector originalTableModel;
    
    public FakturatDalse() {
        initComponents();
       con=ConnectionManager.getConnection();
       OraData();
       fillCombo();
       numrinEFatures();
       numriFiskal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        totaliNeEuro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        qmimi = new javax.swing.JTextField();
        sasia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tabela = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        barkodi = new javax.swing.JTextField();
        emriProd = new javax.swing.JComboBox<>();
        numriFiskal = new javax.swing.JLabel();
        numriFatures = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ParaTeGatshme = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totaliPaTVSH = new javax.swing.JLabel();
        Tvsh = new javax.swing.JLabel();
        kusur = new javax.swing.JLabel();
        artikujt = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ora = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("TOTALI NE EURO");

        totaliNeEuro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totaliNeEuro.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(totaliNeEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totaliNeEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nr.Fiskal");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Barkodi");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Emri Produktit");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Qmimi");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Sasia");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Nr.Fatures");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Data e leshimit te fatures");

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkodi", "Emri i produktit", "Qmimi", "Sasia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela1.getTableHeader().setReorderingAllowed(false);
        tabela.setViewportView(tabela1);
        if (tabela1.getColumnModel().getColumnCount() > 0) {
            tabela1.getColumnModel().getColumn(0).setResizable(false);
            tabela1.getColumnModel().getColumn(1).setResizable(false);
            tabela1.getColumnModel().getColumn(2).setResizable(false);
            tabela1.getColumnModel().getColumn(3).setResizable(false);
        }

        emriProd.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                emriProdPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        numriFiskal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        numriFatures.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numriFiskal, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(numriFatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(barkodi))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emriProd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qmimi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(sasia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numriFatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numriFiskal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qmimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barkodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emriProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(tabela, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("PARA TE GATSHME");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Kusur");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("TVSH E=18,00%");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Totali pa TVSH");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Artikujt");

        totaliPaTVSH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totaliPaTVSH.setText("0.00");

        Tvsh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tvsh.setText("0.00");

        kusur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kusur.setText("0.00");

        artikujt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ParaTeGatshme)
                    .addComponent(totaliPaTVSH, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(Tvsh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kusur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(artikujt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ParaTeGatshme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(kusur, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Tvsh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(totaliPaTVSH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(artikujt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus-40.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete-40.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Broom-40.png"))); // NOI18N
        jButton6.setText("Clear");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cash Register-40.png"))); // NOI18N
        jButton4.setText("Pay");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh-40.png"))); // NOI18N
        jButton1.setText("Refresh");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Ora:");
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(ora);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            public void clear(){
                
                ParaTeGatshme.setText("");
                kusur.setText("");
                artikujt.setText("");
            }
            
            public void OraData(){
                Thread clock=new Thread()
                {
                    @Override
                    public void run(){
                        try {
                            for(;;){
                                Calendar c = new GregorianCalendar();
                                int month = c.get(Calendar.MONTH);
                                int year = c.get(Calendar.YEAR);
                                int day = c.get(Calendar.DAY_OF_MONTH);
                                data.setText(day+"/"+(month+1)+"/"+year);

                                int second = c.get(Calendar.SECOND);
                                int minute = c.get(Calendar.MINUTE);
                                int hour = c.get(Calendar.HOUR);
                                ora.setText(hour+":"+minute+":"+second);
                            
                                sleep(1000);
                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                };
                clock.start();
            }
            
            
            
            public void fillCombo(){
                try {
                    String query = "select barkodi,emriIProduktit,qmimi,sasia from stoku";
                    pst=con.prepareStatement(query);
                    rs=pst.executeQuery();
                    while(rs.next()){
                        String emri = rs.getString("emriIProduktit");
                        emriProd.addItem(emri);
                    }
                    
                } catch (SQLException e) {
                }
            }
            
           
            public void numrinEFatures(){
                try {
                    String query="select nrFatures from faktura";
                    pst=con.prepareStatement(query);
                    rs=pst.executeQuery();
                    while(rs.next()){
                        int nr = rs.getInt("nrFatures");
                        String rez = Integer.toString(nr);
                        numriFatures.setText(rez);
                    }
                    
                } catch (SQLException e) {
                     JOptionPane.showMessageDialog(this, e);
                }
            }
            
            public void numriFiskal(){
                try {
                    String query = "select nrFiskal from faktura";
                    pst=con.prepareStatement(query);
                    rs=pst.executeQuery();
                    while(rs.next()){
                        int nr = rs.getInt("nrFiskal");
                        String rez = Integer.toString(nr);
                        numriFiskal.setText(rez);
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            }
              
                
            
               public void searchProduct(String searchText){
                   DefaultTableModel model = (DefaultTableModel)tabela1.getModel();
                   model.setRowCount(0);
                   for (Object rows : originalTableModel) {
                       Vector rowVector = (Vector)rows;
                       for (Object column : rowVector){
                           if (column.toString().contains(searchText)) {
                               model.addRow(rowVector);
                               break;
                           }
                       }
                   }
               }
        
         
         public void Kusur(){
             double pagesa=0;
             double totali=0;
             double sum=0;
             double result=0;
             
              pagesa = pagesa + Double.parseDouble(ParaTeGatshme.getText());
              totali=totali+ Double.parseDouble(totaliNeEuro.getText());
              
              sum=pagesa-totali;
              result=(int)Math.round(sum*100)/(double)100;
              kusur.setText(Double.toString(result));
              
         }
         
         public void TVSH(){
             double sum=0;
             double tvsh=18;
             double totaliPaTvsh=0;
             double result=0;
             
             totaliPaTvsh = totaliPaTvsh + Double.parseDouble(totaliPaTVSH.getText());             
             sum = (totaliPaTvsh*tvsh)/100;
             result=(int)Math.round(sum*100)/(double)100;
             Tvsh.setText(Double.toString(result));
         }
            
         public void totaliNeEuro(){
             double tvsh=0;
             double totaliPaTvsh=0;
             double sum=0;
             double result=0;
             
             tvsh = tvsh + Double.parseDouble(Tvsh.getText());
             totaliPaTvsh= totaliPaTvsh + Double.parseDouble(totaliPaTVSH.getText());
             sum = totaliPaTvsh+tvsh;
             
             result=(int)Math.round(sum*100)/(double)100;
             totaliNeEuro.setText(Double.toString(result));
         }
         
        public void fshijNgaStoku(){
            try {
                
                       
                for (int i = 0; i < tabela1.getRowCount(); i++) {
                    
                    String query="delete from stoku where barkodi='"+tabela1.getValueAt(i, 0).toString()+"'";
                    pst=con.prepareStatement(query);
                    pst.executeUpdate();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        
         
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clear();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           try{
            DefaultTableModel model = (DefaultTableModel)tabela1.getModel();
            Object [] row = new Object[4];
            row[0] = barkodi.getText();
            row[1] = emriProd.getSelectedItem();
            row[2] = qmimi.getText();
            row[3] = sasia.getText();
            
           
            if(barkodi.getText().isEmpty() || qmimi.getText().isEmpty() || sasia.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Te gjitha fushat duhet te jene te plotesuara");
            }else{
                model.addRow(row);   
                
              String query="insert into fakturaDalese(barkodi,emriIProduktit,qmimi,sasia,nrFatures,nrFiskal) values ('"+barkodi.getText()+"','"+emriProd.getSelectedItem()+"','"+qmimi.getText()+"','"+sasia.getText()+"','"+numriFatures.getText()+"','"+numriFiskal.getText()+"')";
              st=con.createStatement();
              st.executeUpdate(query);
               Totali();
                TVSH();
                totaliNeEuro();
                totaliArtikujt();
                }
            }catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e);
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed
            
            public void Totali(){
               double sum=0;
               double result=0;
                for (int i = 0; i < tabela1.getRowCount(); i++) {
                    sum=sum+Double.parseDouble(tabela1.getValueAt(i,2).toString());
                }
                result=(int)Math.round(sum*100)/(double)100;
                totaliPaTVSH.setText(Double.toString(result));
                
            }
            
            public void totaliArtikujt(){
                int sum=0;
                for (int i = 0; i < tabela1.getRowCount(); i++) {
                    sum=sum+Integer.parseInt(tabela1.getValueAt(i, 3).toString());
                }
                artikujt.setText(Integer.toString(sum));
            }
           
            
    private void emriProdPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_emriProdPopupMenuWillBecomeInvisible
          try {
                String sql = "select barkodi,emriIProduktit,qmimi,sasia from stoku where emriIProduktit=?";
            
                pst = con.prepareStatement(sql);
                pst.setString(1, (String)emriProd.getSelectedItem());
                rs=pst.executeQuery();
                
                
                while(rs.next()){
             
                barkodi.setText(rs.getString("barkodi"));
                qmimi.setText(rs.getString("qmimi"));
                sasia.setText(rs.getString("sasia"));
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
                }
            
            
    }//GEN-LAST:event_emriProdPopupMenuWillBecomeInvisible

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         DefaultTableModel model = (DefaultTableModel)tabela1.getModel();
        int i = tabela1.getSelectedRow();
        if(i>=0){
            model.removeRow(i);
            Totali();
             TVSH();
             totaliNeEuro();
             totaliArtikujt();
        }else{
            JOptionPane.showMessageDialog(this, "Zgjedhni rreshtin qe deshironi te fshini"
                    ,"Warning",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            double pagesa=0;
            double totali=0;
            double kusuri=0;
             pagesa = pagesa + Double.parseDouble(ParaTeGatshme.getText());
             totali = totali + Double.parseDouble(totaliNeEuro.getText());
             Kusur();
            
             if(ParaTeGatshme.getText().equalsIgnoreCase("") || pagesa<totali) {
                    JOptionPane.showMessageDialog(this, "Fusha nuk eshte plotesuar ose keni dhene para te gatshme me pak se totali qe duhet te paguhet"
                            ,"Warning",JOptionPane.WARNING_MESSAGE);
                         kusur.setText(Double.toString(kusuri));
                }else{
                       
               
                Object [] options = {"PO","JO"};
                         int n1 = JOptionPane.showOptionDialog(this, "A deshironi ta printoni kete fature",
                        "Delete", JOptionPane.YES_NO_OPTION,
                         JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
                  try{
                    if (n1==0) {
                        
                        String [] options1 = {"Ok","Cancel"};
                        JPanel panel1 = new JPanel();
                        JLabel lb1 = new JLabel("Shkruani emrin e faktures qe deshironi te ruani si pdf");
                        JTextField txt = new JTextField(10);
                        panel1.add(lb1);
                        panel1.add(txt);
                         int selectedOption = JOptionPane.showOptionDialog(null, panel1, "Ruaj Fakturen",
                        JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options1, options1[1]);
                        String emri = txt.getText();
                        
                         if (selectedOption == JOptionPane.OK_OPTION) {
                             if (txt.getText().isEmpty()) {
                                 JOptionPane.showMessageDialog(this, "Shkruani emrin e faktures",
                                         "Warning",JOptionPane.WARNING_MESSAGE);
                                         
                             }else{
                    JOptionPane.showMessageDialog(this, "U Printua");
                    fshijNgaStoku();
                    int numriF = Integer.parseInt(numriFatures.getText());
                    int sum = numriF+1;
                    int numriFisk = Integer.parseInt(numriFiskal.getText());
                    int sum1 = numriFisk+1;
                    
                    String text = Integer.toString(sum);
                    String text1 = Integer.toString(sum1);

                    String query = "insert into faktura(nrFatures,nrFiskal) values('"+sum+"','"+sum1+"')";
                    pst=con.prepareStatement(query);
                    pst.executeUpdate();
                    
                        Document document = new Document();  
                        PdfWriter.getInstance(document, new FileOutputStream(emri+".pdf"));
                        document.open();
                        document.add(new Paragraph("Minimarketi UBT"));
                        document.add(new Paragraph("-----------------------------------------------------------------------------------------------------------------------\n\n"));
                        PdfPTable pdfTable = new PdfPTable(tabela1.getColumnCount());
                        for (int i = 0; i < tabela1.getColumnCount(); i++) {
                        pdfTable.addCell(tabela1.getColumnName(i));
                    }
                        for (int rows = 0; rows < tabela1.getRowCount(); rows++) {
                            for (int cols = 0; cols < tabela1.getColumnCount(); cols++) {
                                pdfTable.addCell(tabela1.getModel().getValueAt(rows, cols).toString());
                            }

                    }
                        document.add(pdfTable);
                        document.add(new Paragraph("-----------------------------------------------------------------------------------------------------------------------\n\n"));
                        document.add(new Paragraph("Totali ne Euro: "+totaliNeEuro.getText()+"\n\n"));
                        document.add(new Paragraph("Para te gatshme: "+ParaTeGatshme.getText()+"\n\n"));
                        document.add(new Paragraph("Tvsh: "+Tvsh.getText()+"\n\n"));
                        document.add(new Paragraph("Totali pa TVSH: "+totaliPaTVSH.getText()+"\n\n"));
                        document.add(new Paragraph("Artikujt: "+artikujt.getText()+"\n\n"));
                        document.add(new Paragraph("Numri i Faktures: "+numriFatures.getText()+"\n\n"));
                        document.add(new Paragraph("Numri Fiskal: "+numriFiskal.getText()+"\n\n"));   
                        document.add(new Paragraph("Data e leshimit te faktures: "+data.getText()+"\n\n"));
                        document.add(new Paragraph("Ora e leshimit te faktures: "+ora.getText()+"\n\n"));
                        document.close();
                             }
                        }
                }else if(n1==1){
                    JOptionPane.showMessageDialog(this, "Nuk Printua");
                    
                }      
                  
                  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            }
               
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            emriProd.removeAllItems();
            fillCombo();
            numrinEFatures();
            numriFiskal();
    }//GEN-LAST:event_jButton1ActionPerformed

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ParaTeGatshme;
    private javax.swing.JLabel Tvsh;
    private javax.swing.JLabel artikujt;
    private javax.swing.JTextField barkodi;
    private javax.swing.JLabel data;
    private javax.swing.JComboBox<String> emriProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel kusur;
    private javax.swing.JLabel numriFatures;
    private javax.swing.JLabel numriFiskal;
    private javax.swing.JMenu ora;
    private javax.swing.JTextField qmimi;
    private javax.swing.JTextField sasia;
    private javax.swing.JScrollPane tabela;
    private javax.swing.JTable tabela1;
    private javax.swing.JLabel totaliNeEuro;
    private javax.swing.JLabel totaliPaTVSH;
    // End of variables declaration//GEN-END:variables
}
