/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekti;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Besnik
 */
public class fakturaHyrese extends javax.swing.JInternalFrame {

    /**
     * Creates new form fakturaHyrese
     */
    private Connection con;
    private Statement st;
    private ResultSet rs;
    private PreparedStatement pst;
    
    public fakturaHyrese() {
        initComponents();
        con=ConnectionManager.getConnection();
        fillCombo();
    }
            
    
             public void fillCombo(){
                 try {
                     String query="select distinct nrFatures from fakturaDalese";
                     st=con.createStatement();
                     rs=st.executeQuery(query);
                     while(rs.next()){
                         int i = rs.getInt("nrFatures");
                         String e = Integer.toString(i);
                         fatura.addItem(e);
                     }
                 } catch (SQLException e) {
                     JOptionPane.showMessageDialog(this, e);
                 }
             }
             
             public void qmimiTotal(){
               try {
                   String sql = "SELECT SUM(qmimi) 'Sum'  FROM fakturadalese WHERE nrFatures='"+fatura.getSelectedItem()+"'";
                   pst=con.prepareCall(sql);
                   rs=pst.executeQuery();
                   while(rs.next()){
                        qmimi.setText(rs.getString("sum"));
                        Double i = Double.parseDouble(qmimi.getText());
                        Double t = (int)Math.round(i*100)/(double)100;
                        qmimi.setText(Double.toString(t)+"€");
                   }
                 } catch (SQLException e) {
                     JOptionPane.showMessageDialog(this, e);
                 }
             }
             
             public void totaliProdukteve(){
                 try {
                     String sql="SELECT SUM(`sasia`) 'Totali' FROM fakturadalese WHERE nrFatures='"+fatura.getSelectedItem()+"'";
                     pst=con.prepareCall(sql);
                     rs=pst.executeQuery();
                     while(rs.next()){
                        totaliProd.setText(rs.getString("totali"));
                        Double i = Double.parseDouble(totaliProd.getText());
                        double t = (int)Math.round(i*100)/(double)100;
                        totaliProd.setText(Double.toString(t));
                     }
                 } catch (SQLException e) {
                     JOptionPane.showMessageDialog(this, e);
                 }
             }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fatura = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        qmimi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totaliProd = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Zgjedhni numrin e faktures qe deshironi");

        fatura.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                faturaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkodi", "Emri i produktit", "Qmimi", "Sasia", "NrFatures", "NrFiskal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
            tabela.getColumnModel().getColumn(4).setResizable(false);
            tabela.getColumnModel().getColumn(5).setResizable(false);
        }

        qmimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Qmimi total i fatures se caktuar: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Totali i produkteve:");

        totaliProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(qmimi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(totaliProd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(qmimi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(totaliProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void faturaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_faturaPopupMenuWillBecomeInvisible
         try {
                String query = "select barkodi,emriIProduktit,qmimi,sasia,nrFatures,nrFiskal from fakturaDalese where nrFatures=?";
                DefaultTableModel model = (DefaultTableModel)tabela.getModel();
                pst = con.prepareStatement(query);
                pst.setString(1, fatura.getSelectedItem().toString());
                rs=pst.executeQuery();
                model.setRowCount(0);
                while(rs.next()){
                     Object [] row = new Object[6];
                     row[0] = rs.getInt("barkodi");
                     row[1] = rs.getString("emriIProduktit");
                     row[2] = rs.getDouble("qmimi");
                     row[3] = rs.getInt("sasia");
                     row[4] = fatura.getSelectedItem();
                     row[5] = rs.getInt("nrFiskal");
                     model.addRow(row);
                     
                }
                    qmimiTotal();
                    totaliProdukteve();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
                }
            
    }//GEN-LAST:event_faturaPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel qmimi;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel totaliProd;
    // End of variables declaration//GEN-END:variables
}
