/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekti;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Besnik
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private static Connection con;
    private static PreparedStatement pst;
    private static ResultSet rs;
            
    public Login() {
       initComponents();
        con=ConnectionManager.getConnection(); 
        
    }
            
            //Metoda me mbyll ni frame 
            public void close(){
                WindowEvent closeEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
                Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeEvent);
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);
        getContentPane().add(username);
        username.setBounds(280, 70, 130, 30);

        label1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label1.setText("Username:");
        getContentPane().add(label1);
        label1.setBounds(110, 60, 130, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 140, 100, 30);
        getContentPane().add(password);
        password.setBounds(280, 140, 130, 30);

        clear.setBackground(new java.awt.Color(250, 250, 250));
        clear.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(370, 270, 150, 50);

        jButton1.setBackground(new java.awt.Color(250, 250, 250));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1490136278_login.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 270, 150, 50);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Roli:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 200, 50, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Puntor/e" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(290, 200, 90, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginBackground.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 640, 340);

        setSize(new java.awt.Dimension(656, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
            username.setText("");
            password.setText("");
            
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
           try {
              
               String query="select * from loginUsers where username=? and password=? and roli=?";
               int count=0;
               pst=con.prepareStatement(query);
               pst.setString(1, username.getText());
               pst.setString(2, password.getText());
               String value = jComboBox1.getSelectedItem().toString();
               pst.setString(3, value);
               rs=pst.executeQuery();
               while(rs.next()){
                   count=count+1;
               }
              
               
               if(value.equals("Admin")){
                   if(count==1){
                       close();
                     AdminForma af = new AdminForma();
                       af.setVisible(true);
                      
                   }else if(username.getText().isEmpty() && password.getText().isEmpty()){
                      JOptionPane.showMessageDialog(this, "Plotesoni fushat per username dhe password"
                              , "Login Error", JOptionPane.WARNING_MESSAGE);
                   }else if(username.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Plotesoni fushen per username"
                              , "Login Error", JOptionPane.WARNING_MESSAGE);
                   }else if(password.getText().isEmpty()){
                       JOptionPane.showMessageDialog(this, "Plotesoni fushen per password"
                              , "Login Error", JOptionPane.WARNING_MESSAGE);
                   } 
                   else {
                       JOptionPane.showMessageDialog(this, "Username ose passwordi ose roli nuk eshte i sakte"
                              , "Login Error", JOptionPane.ERROR_MESSAGE);
                   }
           
               } else if(value.equals("Puntor/e")){
                   if(count==1){
                       close();
                       new AppMainForm().setVisible(true);
                    } else if(username.getText().isEmpty() && password.getText().isEmpty()){
                      JOptionPane.showMessageDialog(this, "Plotesoni fushat per username dhe password"
                              , "Login Error", JOptionPane.WARNING_MESSAGE);
                   }else if(username.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Plotesoni fushen per username"
                              , "Login Error", JOptionPane.WARNING_MESSAGE);
                   }else if(password.getText().isEmpty()){
                       JOptionPane.showMessageDialog(this, "Plotesoni fushen per password"
                              , "Login Error", JOptionPane.WARNING_MESSAGE);
                   } else {
                       JOptionPane.showMessageDialog(this, "Username ose passwordi ose roli nuk eshte i sakte"
                              , "Login Error", JOptionPane.ERROR_MESSAGE);
               } 
              
            }
           }catch(SQLException e){
               JOptionPane.showMessageDialog(this, e);
           }        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
