/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekti;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Besnik
 */
public class Puntoret extends javax.swing.JInternalFrame {

    /**
     * Creates new form Puntoret
     */
     private Connection con;
     private Statement st;
     private PreparedStatement pst;
     private ResultSet rs;
    
    public Puntoret() {
        initComponents();
        con=ConnectionManager.getConnection(); 
        fillCombo();
        ShfaqListenEPuntoreve();
    }

    public void fillCombo(){
                try {
                    String query = "select username from loginusers where roli='Puntor/e'";
                    pst=con.prepareStatement(query);
                    rs=pst.executeQuery();
                    while(rs.next()){
                        String emriUserit = rs.getString("username");
                        username.addItem(emriUserit);
                    }
                    
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this,e);
                }
            }
      public ArrayList<AtributetEPuntoreve> listaPuntoreve() {
                    ArrayList<AtributetEPuntoreve> listaPuntoreve = new ArrayList<AtributetEPuntoreve>();
                    String query = "select*from puntoret";
                    try {
                        st=con.createStatement();
                        rs=st.executeQuery(query);
                        AtributetEPuntoreve aep;
                        while(rs.next()){
                            aep=new AtributetEPuntoreve(rs.getInt("ID"),rs.getString("emri"),rs.getString("mbiemri"),
                            rs.getString("gjinia"),rs.getString("username"));
                            listaPuntoreve.add(aep);
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, e);
                    }
                    return listaPuntoreve;
            }
                
                public void ShfaqListenEPuntoreve(){
                    ArrayList<AtributetEPuntoreve> lista = listaPuntoreve();
                    DefaultTableModel model = (DefaultTableModel)tabela.getModel();
                    Object [] row = new Object[5];
                    for (int i = 0; i < lista.size() ; i++) {
                        row[0]= lista.get(i).getID();
                        row[1]= lista.get(i).getEmri();
                        row[2]= lista.get(i).getMbiemri();
                        row[3]= lista.get(i).getGjinia();
                        row[4]= lista.get(i).getUsername();
                        model.addRow(row);
                    }
                }
                
           public void clear(){
               emri.setText("");
               mbiemri.setText("");
           }     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        emri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mbiemri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gjinia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Emri:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Mbiemri:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Gjinia:");

        gjinia.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gjinia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mashkull", "Femer" }));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Username:");

        jToolBar1.setFloatable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus 2 Math-40.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete-40.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Broom Filled-40.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Emri", "Mbiemri", "Gjinia", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
            tabela.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(gjinia, 0, 100, Short.MAX_VALUE)
                                            .addComponent(emri)
                                            .addComponent(mbiemri)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(username, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(gjinia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
        try {
                String query = "insert into puntoret(emri,mbiemri,gjinia,username) values ('"+emri.getText()+"','"+mbiemri.getText()+"','"+gjinia.getSelectedItem()+"','"+username.getSelectedItem()+"')";
                st=con.createStatement();
                if (st.executeUpdate(query)==1) {
                    ShfaqListenEPuntoreve();
                    JOptionPane.showMessageDialog(this, "U insertuan me sukses");
                }else{
                    JOptionPane.showMessageDialog(this, "Nuk u insertuan");
                }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int i = tabela.getSelectedRow();
        TableModel model = tabela.getModel();
        emri.setText(model.getValueAt(i, 1).toString());
        mbiemri.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       DefaultTableModel model = (DefaultTableModel)tabela.getModel();
       String [] options1 = {"Ok","Cancel"};
        JPanel panel = new JPanel();
        JLabel lb1 = new JLabel("Shkruani id e produktit qe deshironi te fshini nga stoku?");
        JTextField txt = new JTextField(10);
        panel.add(lb1);
        panel.add(txt);
        
        int selectedOption = JOptionPane.showOptionDialog(null, panel, "Delete product",
                JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options1, options1[1]);
        
        String text = txt.getText();
        int n = Integer.parseInt(text);
        try {
                String query = "delete from puntoret where ID='"+n+"'";
                st=con.createStatement();
                if (st.executeUpdate(query)==1) {
                    model.setRowCount(0);
                    ShfaqListenEPuntoreve();
                    JOptionPane.showMessageDialog(this, "U fshi me sukses");
                }else{
                    JOptionPane.showMessageDialog(this, "Nuk u insertuan");
                }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       clear();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emri;
    private javax.swing.JComboBox<String> gjinia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField mbiemri;
    private javax.swing.JTable tabela;
    private javax.swing.JComboBox<String> username;
    // End of variables declaration//GEN-END:variables
}
